#!/bin/bash
# use temp file rather than pipes to be more VM linux terminal compatible
# test on both macOS and web access linux VM

fileOne=${1}
fileTwo=${2}
numBytes=24064
tempFile1=${1}.24k
tempFile2=${2}.24k

echo "comparing" ${1} ${2}
head -c ${numBytes} ${fileOne} > ${tempFile1}
head -c ${numBytes} ${fileTwo} > ${tempFile2}
diff -s ${tempFile1} ${tempFile2}
rm ${tempFile1} ${tempFile2}
