#!/bin/bash
# mrfdump shell script
# can handle .gz and .mrf files
# if gz file, must not have customer_ota directory already in directory

headerLength=4
headerName=0x8
panelFirst=0x318
panelSecond=0x31C
logoFirst=0x510
logoSecond=0x514
displayIF=0xE01
imageStart=0x5e00
gzfile=0
dumpPic=0

getopts :l opt
if [ ${opt} == 'l' ]; then
	dumpPic=1
	shift 1
fi

if [[ $1 =~ \.gz$ ]];
then
	gzfile=1
	if [ -e "customer_ota" ]
	then
        	echo "customer_ota directory already exist"
        	exit 1
	fi	
	tar -xzf ${1}
	mrfFile="customer_ota/logo.mrf"
elif [[ $1 =~ \.mrf$ || $1 =~ \.bin$ ]];
then
	mrfFile="${1}"
else
	exit 1
fi

printf "\n"
echo "****" ${1}
printf "\n= MD1ROM Header\n\n"
printf "length hex "
LengthStr="0x$(od -A x4 -t x4 -j${headerLength} -N4 ${mrfFile} | head -1 | cut -b9- | tr -d " \t\r")"
echo ${LengthStr}
echo -n "length MB  "
echo "scale=1;" $((${LengthStr})) / 1048576 | bc -l
printf "name       "
od -c -j${headerName} -N32 ${mrfFile} | head -1 | cut -b9- | tr -d " \t\r0\\"
printf "\n= Panel\n\n"
od -c -j${displayIF} -N4 ${mrfFile} | head -1 | cut -b9- | tr -d " \t\r"
od -A x2 -t u2 -j${panelFirst} -N2 ${mrfFile} | head -1 | cut -b9- | tr -d " \t\r"
od -A x2 -t u2 -j${panelSecond} -N2 ${mrfFile} | head -1 |cut -b9- | tr -d " \t\r"

printf "\n= LOGO\n\n"
logoD1="$(od -A x2 -t u2 -j${logoFirst} -N2 ${mrfFile} | head -1 | cut -b9- | tr -d " \t\r")"
echo ${logoD1}
logoD2="$(od -A x2 -t u2 -j${logoSecond} -N2 ${mrfFile} | head -1 | cut -b9- | tr -d " \t\r")"
echo ${logoD2}
printf "\n"

if [[ "${gzfile}" -eq 1 ]]; then
	rm -rf customer_ota
fi

if [ ${dumpPic} == 1 ] ; then
	dd bs=8 skip=$((${imageStart} / 8)) count=$((${logoD1} * ${logoD2} * 4 /8 )) if=${mrfFile} of=${mrfFile}img.bin
	magick -depth 8 -size ${logoD1}x${logoD2} bgra:${mrfFile}img.bin ${mrfFile}.png 
	rm -rf ${mrfFile}img.bin
fi
